RegisterNetEvent('rp-crime-core:client:policeAlert', function(coords, message)
    local blip = AddBlipForCoord(coords.x, coords.y, coords.z)
    SetBlipSprite(blip, 161)
    SetBlipColour(blip, 1)
    SetBlipFlashes(blip, true)
    BeginTextCommandSetBlipName('STRING')
    AddTextComponentSubstringPlayerName(message)
    EndTextCommandSetBlipName(blip)

    CreateThread(function()
        Wait(45000)
        RemoveBlip(blip)
    end)
end)
